import { Client } from '../types';
import { getAIConfig } from './aiConfigService';

interface GeminiResponse {
  candidates: Array<{
    content: {
      parts: Array<{
        text: string;
      }>;
    };
  }>;
}

export async function enhanceBioWithGemini(client: Client): Promise<string> {
  const bioOriginal = client.content?.bioOriginal || '';

  if (!bioOriginal.trim()) {
    throw new Error('No original bio available to enhance');
  }

  // Get AI configuration
  const config = getAIConfig();
  const GEMINI_API_URL = `https://generativelanguage.googleapis.com/v1beta/models/${config.geminiModel}:generateContent`;

  // Build context from all client data
  const context = buildContextFromClient(client);

  // Use prompt template from config
  const prompt = config.prompts.bioEnhancement
    .replace('{context}', context)
    .replace('{bioOriginal}', bioOriginal);

  try {
    const response = await fetch(`${GEMINI_API_URL}?key=${config.geminiApiKey}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{
            text: prompt
          }]
        }],
        generationConfig: {
          temperature: 0.9,
          topK: 40,
          topP: 0.95,
          maxOutputTokens: 1024,
        }
      })
    });

    if (!response.ok) {
      const errorData = await response.json();
      throw new Error(`Gemini API error: ${errorData.error?.message || response.statusText}`);
    }

    const data: GeminiResponse = await response.json();
    const enhancedBio = data.candidates[0]?.content?.parts[0]?.text;

    if (!enhancedBio) {
      throw new Error('No bio generated by Gemini');
    }

    return enhancedBio.trim();
  } catch (error) {
    console.error('Error calling Gemini API:', error);
    throw error;
  }
}

/**
 * Generate a short AI summary of a client for display in the UI
 */
export async function generateClientSummary(client: Client): Promise<string> {
  // Get AI configuration
  const config = getAIConfig();
  const GEMINI_API_URL = `https://generativelanguage.googleapis.com/v1beta/models/${config.geminiModel}:generateContent`;

  // Build context from client data
  const context = buildContextFromClient(client);

  const prompt = `Generate a 2-3 sentence professional summary for this podcast guest client. The summary should be concise and highlight their expertise and value as a podcast guest.

CLIENT INFORMATION:
${context}

Write a compelling summary that would help a podcast host quickly understand who this person is and why they would be a great guest. Keep it under 50 words.`;

  try {
    const response = await fetch(`${GEMINI_API_URL}?key=${config.geminiApiKey}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{
            text: prompt
          }]
        }],
        generationConfig: {
          temperature: 0.7,
          topK: 40,
          topP: 0.95,
          maxOutputTokens: 256,
        }
      })
    });

    if (!response.ok) {
      const errorData = await response.json();
      throw new Error(`Gemini API error: ${errorData.error?.message || response.statusText}`);
    }

    const data: GeminiResponse = await response.json();
    const summary = data.candidates[0]?.content?.parts[0]?.text;

    if (!summary) {
      throw new Error('No summary generated by Gemini');
    }

    return summary.trim();
  } catch (error) {
    console.error('Error calling Gemini API for summary:', error);
    throw error;
  }
}

function buildContextFromClient(client: Client): string {
  const parts: string[] = [];

  // Identity
  if (client.identity) {
    parts.push(`Name: ${client.identity.firstName} ${client.identity.lastName}`);
    if (client.identity.jobTitle) parts.push(`Current Role: ${client.identity.jobTitle}`);
    if (client.identity.company) parts.push(`Company: ${client.identity.company}`);
  }

  // Goals
  if (client.goals) {
    if (client.goals.professionalGoals) parts.push(`Professional Goals: ${client.goals.professionalGoals}`);
    if (client.goals.workDescription) parts.push(`What They Do: ${client.goals.workDescription}`);
    if (client.goals.missionDescription) parts.push(`Mission: ${client.goals.missionDescription}`);
    if (client.goals.top3Goals) parts.push(`Top 3 Goals: ${client.goals.top3Goals}`);
    if (client.goals.whyNow) parts.push(`Why Now: ${client.goals.whyNow}`);
  }

  // Brand Personality
  if (client.brandPersonality) {
    if (client.brandPersonality.threeAdjectives) parts.push(`Brand Adjectives: ${client.brandPersonality.threeAdjectives}`);
    if (client.brandPersonality.passionTopics) parts.push(`Passion Topics: ${client.brandPersonality.passionTopics}`);
    if (client.brandPersonality.audienceFeeling) parts.push(`How Audience Should Feel: ${client.brandPersonality.audienceFeeling}`);
  }

  // Speaking Topics
  if (client.content?.speakingTopicsOriginal) {
    parts.push(`Speaking Topics: ${client.content.speakingTopicsOriginal}`);
  }
  if (client.content?.speakingTopicsArray && client.content.speakingTopicsArray.length > 0) {
    parts.push(`Key Topics: ${client.content.speakingTopicsArray.join(', ')}`);
  }

  // Achievements & Recognition
  if (client.goals?.successDefinition) {
    parts.push(`Success Definition: ${client.goals.successDefinition}`);
  }

  return parts.join('\n');
}
